### ISSUE TITLE
Can't find import\export menu

### ISSUE THREAD

**Issue by wolfetplayer** [acqu/rtcw-wet-blender-model-tools#1]
Hello to another RTCW\ET enthusiast! So i installed your plugin on Blender 2.8 - I just took "rtcw_et_model_tools" folder in "src" folder and placed it in addons. So everything is alright and the plugins seems to be working. But I just failed to find any import\export menus. Can you please tell me what is wrong?

**Comment by wolfetplayer** [comment]
Got it! All what you need to do is press N button and you can find the addon panel.

**Comment by mino-git** [comment]
Hi there, sorry for the late reply. I see you found the panel already :)

**Comment by mino-git** [comment]
For future reference, there is now a user guide on github pages: https://mino-git.github.io/rtcw-wet-blender-model-tools/user_guide.html
