### ISSUE TITLE
V_hand animation are not working while in-game

### ISSUE THREAD

**Issue by ZAQraven** [acqu/rtcw-wet-blender-model-tools#10]
Hi there. I exporting animated meshes (v_hand with absolute shape key) in v_..._barrel3.mdc

The result in-game this.

https://user-images.githubusercontent.com/79313756/117669071-b866f080-b1d0-11eb-86a3-94e11eff1f86.mp4

Here the blend file.
[Garand_v5.zip](https://github.com/mino-git/rtcw-wet-blender-model-tools/files/6450098/Garand_v5.zip)

**Comment by thunderpwn** [comment]
you are sure the hands also are on tags? binded? since the rest is working?

**Comment by ZAQraven** [comment]
> you are sure the hands also are on tags? binded? since the rest is working?

The hands are also bound on tags of course.

**Comment by ZAQraven** [comment]
I close this issue because this issue was from the source code game.
