### ISSUE TITLE
Error when clicking Export: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by flarn2006** [acqu/rtcw-wet-blender-model-tools#11]
I'm trying to export an MD3, and when I click the Export button, it just pops up the error message in the title, and no file is created.

**EDIT:** This is with a complex model that has all sorts of things (Beziers, various modifiers, constraints, drivers, you name it.) It works fine with a simpler model. Ideally these features should be supported (could you just read the mesh data that's shown in the viewport?) but if not, it should at least give a more descriptive error saying what exactly is wrong. This isn't as big a deal as I thought it was when it seemed like it wasn't working at all though.

**Comment by ZAQraven** [comment]
You can't use various modifiers, except deformed armature. MD3 and MDC are not contained skeletal/bone but use shapes key. So, if your model has skeletal, they will convert it into vertex animation.

**Comment by mino-git** [comment]
Hi there, can you provide me with a log, also the model file if possible.

**Comment by ashifolfi** [comment]
> You can't use various modifiers, except deformed armature. MD3 and MDC are not contained skeletal/bone but use shapes key. So, if your model has skeletal, they will convert it into vertex animation.

@ZAQraven 
can you give an example here as to what you mean by modifiers? I only have armature deform modifiers on and I'm still getting this same exact error with MD3 so I can only assume your definition includes other things as well

**Comment by mino-git** [comment]
As ZAQraven stated, no modifiers except armature is supported. A possible solution might be to apply all your modifiers before export.
