### ISSUE TITLE
.mds import problem (2)

### ISSUE THREAD

**Issue by OurMods13** [acqu/rtcw-wet-blender-model-tools#13]
I'm trying to import a skeleton (.mds), but it fails (Blender 2.80) - **Report: error, unpack requires a buffer of  52 bytes**

 (I'm sure, I have deinstalled the plugin (2.79) (even the files in "AppData\Roaming").

**Comment by mino-git** [comment]
Hi there, can you provide me with the log. You can find it in the system console of blender.

**Comment by OurMods13** [comment]
![CMBS02](https://user-images.githubusercontent.com/81666284/119229296-fc86b900-bb1f-11eb-8ad7-047eacb1b82a.jpg)

**Comment by ZAQraven** [comment]
>**Report: error, unpack requires a buffer of 52 bytes**


I think that happened because you import with the wrong format.

**Comment by ZAQraven** [comment]
Work fine for me.
![Report2](https://user-images.githubusercontent.com/79313756/119229661-459c3480-bb43-11eb-85b7-aa296affd0dd.png)

Make sure you select the right format before import the file (look carefully at filename extension like .mdc, .md3, mdx, and etc).

**Comment by OurMods13** [comment]
![CMBS02](https://user-images.githubusercontent.com/81666284/119229987-f940fc80-bb22-11eb-930c-1bd7589e0cf8.jpg)

**Comment by mino-git** [comment]
Well, from the log i can see that you are importing a file called "smod_american_acs-acu.mds". I do not have that file, seems custom. Can you try and load an .mds from the original game? You use rtcw, right?

**Comment by ZAQraven** [comment]
> You use rtcw, right?

Yes, that's right.

**Comment by mino-git** [comment]
Also you might join our discord if you have one: https://discord.gg/522CKdX6

**Comment by OurMods13** [comment]
https://drive.google.com/file/d/1ptHlhmNRasLIbnpE9OPMJoMApV0b2MXq/view?usp=sharing

It's 'smod_american_acs-acu' from Combat Mission Black Sea.

**Comment by mino-git** [comment]
You did not answer all my questions.

**Comment by mino-git** [comment]
I checked the file via notepad, it does not seem an original .mds file. So again, is this a file from the original game rtcw?

EDIT the file is also way too small (~120kb) to contain any animation data. Normally .mds files are bigger. Even mesh data in a single frame is bigger.

**Comment by thunderpwn** [comment]
is this a medal of honor file?

**Comment by mino-git** [comment]
what @thunderpwn said :)

**Comment by OurMods13** [comment]
> You did not answer all my questions.

Oh, sorry! 

> Can you try and load an .mds from the original game? You use rtcw, right?

Nope, I thought the tool was able to import any .mds files. I use CM wargames series (Battlefront.com), non-hardcoded game files consist of mdr. and mds files. Our community has mdr. import-export plugin for Blender, but mds. not. So, very sad if we won't able to modify .mds

> is this a medal of honor file?
It should be a modern american infantryman.

**Comment by mino-git** [comment]
Ok. Yeah both are formats are called .mds, but as we also spoke on Discord, they are different.

Maybe you can reverse engineer, or ask one of the devs to hand out a specification, so that a coder may write an import export script.

**Comment by SabadashB** [comment]
@mino-git can i join your discord? I have an question

**Comment by mino-git** [comment]
Sure, whats your user account on discord?
