### ISSUE TITLE
Problem Import MDS

### ISSUE THREAD

**Issue by HeX02** [acqu/rtcw-wet-blender-model-tools#15]
Error: unpack requires a buffer of 52 bytes

i use Blender 2.80 

Game Gothic 2
![image](https://user-images.githubusercontent.com/93056421/138729027-7f978c74-ad64-460f-8a92-f7a2b16aecd3.png)

**Comment by wolfetplayer** [comment]
This plugin is made for rtcw/et.
Not for the gothic 2
