### ISSUE TITLE
Incorrect tag positioning while importing .mdc

### ISSUE THREAD

**Issue by wolfetplayer** [acqu/rtcw-wet-blender-model-tools#17]
Animation is not working properly due to incorrect tag positions with .mdc format. 
.md3 working fine.

**Comment by mino-git** [comment]
Hi there, sorry for the late reply. Can you provide me with an example .mdc file where this is happening? Are all .mdc files tag positions / orientations, or are there some working, and some others not? I guess it is an issue with view model tags. These seem to be working different compared to, for example, .mdc head models.

**Comment by wolfetplayer** [comment]
Try knife anims(_hand.mdc)from either ET or RTCW. 
Try to hook up parts with "Attach"  tool and you'll see what I mean.

**Comment by mino-git** [comment]
Hi, this should be fixed now.
