### ISSUE TITLE
exported MDS make game crash

### ISSUE THREAD

**Issue by PSGAPSGA** [acqu/rtcw-wet-blender-model-tools#18]
Hello, 

thanks for your good tools.
I'm modding models for RTCW with your tools, but modded MDS makes game crash.
For the test, I imported original MDS file & set frame then exported directly. But this MDS file still make game crash.

Do you have any suggestion? 
Thanks & best regards

**Comment by PSGAPSGA** [comment]
I downloaded latest tools from github & problem solved. thanks

**Comment by mino-git** [comment]
Sorry, my fault.

There is currently a mismatch in downloadable versions. The repo download is the latest one, and it contains the fixes regarding the MDS issues you stumbled upon. The download from the website is 1 version behind. I need to update that!
