### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by orange451** [acqu/rtcw-wet-blender-model-tools#19]
I tried this on 3 versions of blender (2.73, 2.83, 2.92). I installed by adding the zip file from downloads page. It appears in my addons folder. There is no model format in the import dropdown that would suggest it is getting installed.

**Comment by orange451** [comment]
Found it... Why would you design the plugin to be used this way? Seems counter-intuitive from every other blender plugin I've used over the years

**Comment by mino-git** [comment]
Hi, this was done for good reasons. At first, the import / export of mdm / mdx file format needs two file locations. The import / export dialog of blender does only allow 1 file pointer, and so the ui was limited if i hooked into the import / export category. The other reason was that i needed more ui elements for additional features, like reading skin files, shading, tag attachments, unzipping. So i created it at another place, where i had more ui elements to create and have there for the user to interact with the addon.
