### ISSUE TITLE
Is MDS export valid?

### ISSUE THREAD

**Issue by Elber88** [acqu/rtcw-wet-blender-model-tools#2]
He there! 
I was trying to import original MDS models/players/infantryss/body.mds - that works correct, but export this model back to MDS makes it invisible in game. Is rtcw mds exporter valid? Maybe I was doing smth wrong. For example - MDC export works perfectly. Please, help.
With respects..

**Comment by mino-git** [comment]
Hi there, MDS export should work.

Check your file size after export, is it the same? If not, i will have a look. I never tested mds models ingame.

**Comment by Elber88** [comment]
> Hi there, MDS export should work.
> 
> Check your file size after export, is it the same? If not, i will have a look. I never tested mds models ingame.

original models: models/players/infantryss/body = 5 824 908 bytes
5 824 908
exported: the same
Result in the game in attached screenshots. 
Please, have a look, or try to test mds models in game.
Thanks in forward.

![shot0001](https://user-images.githubusercontent.com/42680782/70030634-4e492580-15b2-11ea-9120-aa856ea73e52.jpg)
![shot0002](https://user-images.githubusercontent.com/42680782/70030635-4e492580-15b2-11ea-8e1c-bed748e44598.jpg)
![shot0003](https://user-images.githubusercontent.com/42680782/70030636-4ee1bc00-15b2-11ea-8854-94d0d7fc2d51.jpg)

Exported body.mds in zip 

[body.zip](https://github.com/mino-git/rtcw-wet-blender-model-tools/files/3915280/body.zip)

**Comment by mino-git** [comment]
Gonna have a look, but gonna take a while, probably till next week.

**Comment by mino-git** [comment]
Hi again, there was something wrong with the header info, it should be fixed now.

In the coming months i will make a new version for download, meanwhile just download the latest version here on github. Thanks for the report!

P.S. there is still an issue with tag orientations, i am working on it :)
