### ISSUE TITLE
MDM\MDX to MDS

### ISSUE THREAD

**Issue by ShsYoshik** [acqu/rtcw-wet-blender-model-tools#3]
Hello. 
I try convert body from W: ET to RtCW. But I have error 
"write() missing 1 required positional argument: 'collapse_frame'"

If use method import then export, I got another error
"list index out of range"

https://i.imgur.com/QypDFDS.png

**Comment by ShsYoshik** [comment]
Also have same issue when try import .mds from RtCW: Operation Resurrection (PS2)
"list index out of range"

**Comment by mino-git** [comment]
Hi Yoshik,

can you post me the .mds model you "import then export"?

For "write() missing 1 required positional argument: 'collapse_frame'", i missed that, thanks for reporting.

Will come up with a patch as soon as possible.

**Comment by ShsYoshik** [comment]
Here files https://dropmefiles.com/Py0w3

**RtCW .mds to RtCW .mds** - all work fine
**W:ET .mdm\mdx to RtCW .mds** - eror's "write() missing 1 required positional argument: 'collapse_frame'" or "list index out of range"
**Xbox RtCW .mds to PC RtCW .mds** - "list index out of range"

Hope this information help you.

**Comment by mino-git** [comment]
Hi again,

i have put together a quick fix. You can download the latest version here on github.

Keep also in mind that you might run into orientation issues with .mds tags. I still try to find the time to fix this.

Thanks for reporting again!
