### ISSUE TITLE
Certain Tags Not Animating Properly

### ISSUE THREAD

**Issue by houthakker888** [acqu/rtcw-wet-blender-model-tools#4]
I imported an MDS file, it works in Blender and exports fine. However the exported file has all non-body tags (head, weapon, etc.) incorrectly animated. It doesn't matter what format I export into, and happens even if immediately exported without any edit.

Checking in MDSView, I found that these "tag_*" bones are supposed to have flags:1, whereas the exported bones have flags:0. Did I do something wrong or is this an issue with the addon?

**Comment by mino-git** [comment]
Hi there, you are correct! There is a problem with mds tags. I will look into it as soon as i find some free time. Thanks for report!

**Comment by houthakker888** [comment]
Thanks for the reply, that's good to know. 
I tried adding the flags with hex editor but it didn't work. I mean it worked on the file but in game it's still wrong.
Hopefully it can be fixed on the export end so I don't have to do all the animating again🤔

**Comment by mino-git** [comment]
Hi again, a quick fix can now be downloaded here on github. Good hint about the flags, because these were part of the problem. If problem persists, just reopen. Thanks again for the report!
