### ISSUE TITLE
.mds import problem

### ISSUE THREAD

**Issue by OurMods13** [acqu/rtcw-wet-blender-model-tools#6]
I have a problem (I tried to import .mds, Blender 2.79 and 2.8):
![ALYS5436_1200](https://user-images.githubusercontent.com/81666284/113087369-24c2fd00-91ec-11eb-8a50-e590c3df95ba.jpg)

**Comment by mino-git** [comment]
Hi, sry for the late reply. There is currently only support for blender 2.8, blender 2.79 is not supported.

Make sure to deinstall the plugin (even the files in "AppData\Roaming"), then give it another shot with bl2.8.
