### ISSUE TITLE
V_hand model animation.

### ISSUE THREAD

**Issue by ZAQraven** [acqu/rtcw-wet-blender-model-tools#7]
Hi there, just want to know. Is there possible to make an animation of the hand in view player model?
If it does. How is it work? 

I know it will be converted from armature into shapekeys.
The point is. How do I export it?

**Comment by thunderpwn** [comment]
hey @ZAQraven V_hands are own animations.. they are frame animations
program that support this I belive is Blender and misfitmodel.

**Comment by mino-git** [comment]
what @thunderpwn said :)

**Comment by mino-git** [comment]
What would be good to know, do you try to make a reload animation? Or do you want to animate the mesh, for example, to make a taunt? And what kind of mesh do you have for export, a skeletal mesh?

**Comment by ZAQraven** [comment]
> What would be good to know, do you try to make a reload animation? Or do you want to animate the mesh, for example, to make a taunt? And what kind of mesh do you have for export, a skeletal mesh?

Yes, not just reload animation but also other animation (shooting, idle, draw, etc.). And yeah I want to use skeletal mesh for the view player model.

![RTCW1](https://user-images.githubusercontent.com/79313756/117533176-9bd28900-b015-11eb-8019-c608f4ad5bad.png)
Uses skeletal on hand only. The weapon will uses tags.

**Comment by thunderpwn** [comment]
skeletal won work

**Comment by thunderpwn** [comment]
@ZAQraven join our discord if you have one:

https://discord.gg/QfyaAZAexr

**Comment by mino-git** [comment]
As i was making some steps with vhand animations, i could see that all that was possible is to animate athe tag (location, rotation), but not the mesh itself. As the tag system is fairly hardcoded in et source code one can:

- modify a mesh (remains static anyway)
- modify the tag animation, which in turn animates the meshes location / orientation

As mdc or md3 files use vertex based animation, there is no trigger point in et source code to trigger those vertex based animations. This would be actually so cool to have single hand gestures.
