### ISSUE TITLE
Wrong orientation/ direction of tag's animation in Blender.

### ISSUE THREAD

**Issue by ZAQraven** [acqu/rtcw-wet-blender-model-tools#8]
https://user-images.githubusercontent.com/79313756/117532883-ed7a1400-b013-11eb-9963-81be9f48983a.mp4

Hi there.
When I import the file the orientation of tags are wrong way, It was imported with MDC file format.
Procedure:
1. The first order is import v_..._hand.mdc
2. Import all .mdc then attach the object into the tags that belong v_..._hand.mdc

 Could you fix it, please?.

Here the file I tested.
[m3-original-files.zip](https://github.com/mino-git/rtcw-wet-blender-model-tools/files/6445543/m3-original-files.zip)

**Comment by ZAQraven** [comment]
And after exporting the md3/mdc. When In-game, The tags have the wrong orientation/directional.
https://user-images.githubusercontent.com/79313756/117579690-3b7b3e80-b11e-11eb-9701-df3746ffa936.mp4
https://user-images.githubusercontent.com/79313756/117792147-38df2d00-b275-11eb-95b3-3ffa3a25aad1.mp4



![184164194_214375103551154_1064068377616224609_n](https://user-images.githubusercontent.com/79313756/117579723-5cdc2a80-b11e-11eb-9b6a-9f6c0c5ea7b0.png)

**Comment by ZAQraven** [comment]
Seems the problem is the math in mdi/util.py 
lines #289 to # 345.
But, I kind of doesn't understand the operation of trigonometry (sin, and cos).

**Comment by wolfetplayer** [comment]
Resolved yet? I have the same problem

**Comment by mino-git** [comment]
Hi, this should be fixed now.
